Project_Edelweiss/Project_Edelweiss/Controllers/AgentController.cs
using System;
using Edelweiss.BLL.DTO;
using Edelweiss.BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Project_Edelweiss.Controllers
{
    public class AgentController : Controller
    {
        IAgentService agentService;
        ICountryService _countryService;
        public AgentController(IAgentService agentService, ICountryService countryService)
        {
            this.agentService = agentService;
            _countryService = countryService;
        }


        // GET: Agent
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int page = 1)
        {
            return View(agentService.GetAll(page));
        }

        // GET: Agent/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                ModelState.AddModelError(string.Empty, "Агент не найден");
                return RedirectToAction("SearchAgentForBlock", "Account");
            }
            ViewBag.Promo = agentService.GetAgent(id).ImagePromo;
            ViewBag.Logo = agentService.GetAgent(id).ImageLogo;

            return View(agentService.Get(id));
        }

        [Authorize(Roles = "Admin,Agent,Cashier,Controller,ControllerExtended")]
        public ActionResult General(int id)
        {
            ViewBag.Promo = agentService.GetAgent(id).ImagePromo;
            ViewBag.Logo = agentService.GetAgent(id).ImageLogo;

            return View(agentService.Get(id));
        }

        // GET: Agent/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewBag.agents = new SelectList(agentService.GetAll(), "Id", "Name");
            ViewBag.countries = new SelectList(_countryService.SortByPopularity(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(AgentDTO agentDTO)
        {
            agentService.Create(agentDTO);
            return RedirectToAction(nameof(Index));
        }


        // GET: Agent/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            ViewBag.agents = new SelectList(agentService.GetAll(), "Id", "Name");
            ViewBag.countries = new SelectList(_countryService.SortByPopularity(), "Id", "Name");
            return View(agentService.Get(id));
        }

        // POST: Agent/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(AgentDTO model)
        {
            agentService.Update(model);
            return RedirectToAction(nameof(Index));
        }

        // GET: Agent/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            return View((agentService.Get(id)));
        }

        

        // POST: Agent/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteItem(int id)
        {
            agentService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Project_Edelweiss/Project_Edelweiss/Controllers/RangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Edelweiss.BLL.DTO;
using Edelweiss.BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Project_Edelweiss.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RangeController : Controller
    {
        private IRangeService _service;
        public RangeController(IRangeService service)
        {
            _service = service;
        }
        // GET: Range
        public ActionResult Index(int page = 1)
        {
            return View(_service.GetAll(page));
        }

        // GET: Range/Details/5
        public ActionResult Details(int id)
        {
            return View(_service.Get(id));
        }

        // GET: Range/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Range/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RangeDTO range)
        {
            try
            {
                _service.Create(range);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }

        // GET: Range/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_service.Get(id));
        }

        // POST: Range/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RangeDTO range)
        {
            try
            {
                _service.Update(range);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }

        // GET: Range/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_service.Get(id));
        }

        // POST: Range/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteItem(int id)
        {
            try
            {
                _service.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }
    }
}

Project_Edelweiss/Project_Edelweiss/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Edelweiss.DAL.EF;
using Edelweiss.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Project_Edelweiss.Models;

namespace Project_Edelweiss.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        readonly RoleManager<IdentityRole> _roleManager;
        readonly UserManager<User> _userManager;
        private readonly ApplicationDbContext _context;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager,
            ApplicationDbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
        }
        public IActionResult Index()
        {//--------------------------------
          //  IdentityResult result = await _userManager.SetLockoutEnabledAsync(user, true);
            return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create()
        {
            return View();
        } 

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
        //---------------------------------------------------------------------------------
      

    }
}

Project_Edelweiss/Project_Edelweiss/Controllers/TariffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using Edelweiss.BLL.DTO;
using Edelweiss.BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Project_Edelweiss.Controllers
{
    public class TariffController : Controller
    {
        private ITariffService _tariffService;
        private ICountryService _countryService;
        private ICurrencyService _currencyService;
        private IAgentService _agentService;
        private IRangeService _rangeService;

        public TariffController(ITariffService tariffService, 
            ICountryService countryService,
            ICurrencyService currencyService,
            IAgentService agentService,
            IRangeService rangeService)
        {
            _tariffService = tariffService;
            _countryService = countryService;
            _currencyService = currencyService;
            _agentService = agentService;
            _rangeService = rangeService;
        }
        // GET: Tariff
        [Authorize(Roles = "Admin, Agent, Cashier, Controller,ControllerExtended")]
        public ActionResult Index(int page = 1)
        {
            return View(_tariffService.GetAll(page));
        }

        // GET: Tariff/Details/5
        [Authorize(Roles = "Admin, Agent, Cashier, Controller,ControllerExtended")]
        public ActionResult Details(int id)
        {
            return View(_tariffService.Get(id));
        }

        // GET: Tariff/Copy
        [Authorize(Roles = "Admin")]
        public ActionResult Copy(int id)
        {
            ViewBag.agents = new SelectList(_agentService.GetAll(), "Id", "Name");
            ViewBag.currencies = new SelectList(_currencyService.GetAll(), "Id", "Name");
            ViewBag.countries = new SelectList(_countryService.GetAll(), "Id", "Name");
            ViewBag.rangesMin = new SelectList(_rangeService.GetAll(), "Id", "MinValue");
            ViewBag.rangesMax = new SelectList(_rangeService.GetAll(), "Id", "MaxValue");


            return View(_tariffService.Get(id));
        }

        // GET: Tariff/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.agents = new SelectList(_agentService.GetAll(), "Id", "Name");
            ViewBag.currencies = new SelectList(_currencyService.GetAll(), "Id", "Name");
            ViewBag.countries = new SelectList(_countryService.GetAll(), "Id", "Name");
            ViewBag.rangesMin = new SelectList(_rangeService.GetAll(), "Id", "MinValue");
            ViewBag.rangesMax = new SelectList(_rangeService.GetAll(), "Id", "MaxValue");


            return View();
        }

        // POST: Tariff/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TariffDTO model)
        {
            try
            {
                _tariffService.Create(model);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }

        // GET: Tariff/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            ViewBag.agents = new SelectList(_agentService.GetAll(), "Id", "Name");
            ViewBag.currencies = new SelectList(_currencyService.GetAll(), "Id", "Name");
            ViewBag.countries = new SelectList(_countryService.GetAll(), "Id", "Name");
            ViewBag.rangesMin = new SelectList(_rangeService.GetAll(), "Id", "MinValue");
            ViewBag.rangesMax = new SelectList(_rangeService.GetAll(), "Id", "MaxValue");
            return View(_tariffService.Get(id));
        }

        // POST: Tariff/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TariffDTO model)
        {
            try
            {
                _tariffService.Update(model);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }

        // GET: Tariff/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            return View(_tariffService.Get(id));
        }

        // POST: Tariff/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteItem(int id)
        {
            try
            {
                _tariffService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, ex);
            }
        }
    }
}

Project_Edelweiss/Project_Edelweiss/Views/Shared/ErrorSearch.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Project_Edelweiss/Project_Edelweiss/Views/Shared/ExeptionView.cshtml
@{
    ViewData["Title"] = "ExeptionView";
}

<h2>Что-то поломалось!!!</h2>

Project_Edelweiss/Project_Edelweiss/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/countries/phonecode.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="~/font-awesome/css/font-awesome.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/vendor.min.css" />
        <link rel="stylesheet" type="text/css" href="styles/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
              integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
              crossorigin="anonymous">
    </environment>
</head>
<body>
    <header>
        @{
            Html.RenderPartial("_NavigationMenu");
        }
    </header>

    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 bd-sidebar">
            <div class="list-group">
                @if (User.IsInRole("Cashier") || User.IsInRole("ControllerExtended"))
                {
                    <label class="list-group" id="main-menu">@Localizer["Clients"]</label>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Client" asp-action="Index">@Localizer["ClientSearch"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Client" asp-action="Create">@Localizer["ClientCreate"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Tariff" asp-action="Index">@Localizer["Tariffs"]</a>
                        </li>
                    </ul>
                    <label class="list-group" id="main-menu">@Localizer["CashierMenu"]</label>
                    <ul class="list-group">
                        @*<li class="list-group-item list-group-item-action">
                                <a asp-action="AllCreated" asp-controller="SysTransactions">@Localizer["AllCreated"]</a>
                                     <a asp-action="AllCreated" asp-controller="SysTransactions">@Localizer["AllCreated"]</a>
                            </li>*@
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="SysTransactions" asp-action="Sort">@Localizer["Search"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllByStatus" asp-controller="SysTransactions" asp-route-status="Created">@Localizer["AllByThisAgent"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllByStatus" asp-controller="SysTransactions" asp-route-status="ToPay">@Localizer["AllToPay"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllToPayOff" asp-controller="SysTransactions">@Localizer["AllToPayOff"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllByStatus" asp-controller="SysTransactions" asp-route-status="ToPayOff">@Localizer["ToPayOff"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllByStatus" asp-controller="SysTransactions" asp-route-status="Issued">@Localizer["Issued"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllCanceled" asp-controller="SysTransactions">@Localizer["AllCanceled"]</a>
                        </li>
                        @*<a class="list-group-item list-group-item-action" asp-action="AllByStatus" asp-controller="SysTransactions" asp-route-status="Canceled">@Localizer["Canceled"]</a>*@
                    </ul>

                }
                @if (User.IsInRole("Controller") || User.IsInRole("ControllerExtended"))
                {
                    <label class="list-group" id="main-menu">@Localizer["Controller"]</label>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllByStatus" asp-controller="SysTransactions" asp-route-status="Approved">@Localizer["Approved"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllByThisAgent" asp-controller="SysTransactions">@Localizer["AllByThisController"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-action="AllByStatus" asp-controller="SysTransactions" asp-route-status="Confirmed">@Localizer["Confirmed"]</a>
                        </li>
                        @if (User.IsInRole("ControllerExtended"))
                        {
                            <li class="list-group-item list-group-item-action">
                                <a class="list-group-item-action" asp-action="AllByThisSubAgentIncludParentAgent" asp-controller="SysTransactions">@Localizer["AllByThisSubAgentIncludParentAgent"]</a>
                            </li>
                        }
                    </ul>

                }
                @if (User.IsInRole("Admin"))
                {
                    <label class="list-group" id="main-menu">@Localizer["Admin"]</label>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="SysTransactions" asp-action="Sort">@Localizer["Search"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Agent" asp-action="Index">@Localizer["AgentList"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Client" asp-action="Index">@Localizer["ClientSearch"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Country" asp-action="Index">@Localizer["CountryList"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="SysTransactions" asp-action="Index" asp-route-role="@User.IsInRole("Admin")">@Localizer["TransactionList"]</a>
                        </li>
                        @*<li class="list-group-item list-group-item-action">
                            <a class="list-group-item list-group-item-action" asp-controller="SysTransactions" asp-action="Sort">@Localizer["SortTest"]</a>
                        </li>*@
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Role" asp-action="Index">@Localizer["Roles"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Currency" asp-action="Index">@Localizer["Currencies"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Tariff" asp-action="Index">@Localizer["Tariffs"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Range" asp-action="Index">@Localizer["Ranges"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Commission" asp-action="Index">@Localizer["Commissions"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="CellPhoneMask" asp-action="Index">@Localizer["CellPhoneMask"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Account" asp-action="SearchAgentForBlock">@Localizer["FindAgent"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Account" asp-action="SearchUserForBlock">@Localizer["FindUser"]</a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <a class="list-group-item-action" asp-controller="Account" asp-action="Register">@Localizer["Register"]</a>
                        </li>
                    </ul>

                }
            </div> @*col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content*@
        </div>
        <div class="col-12 col-md-8">            
            @RenderBody()
        </div>
    </div>

    <div>

    </div>
    <div class="admin-menu-list">

    </div>
    <div>

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/vendor.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>


<script>
    $(function () {
        $("#dateFieldFirst").datepicker();
        $("#dateFieldSecond").datepicker();
    });
</script>

Project_Edelweiss/Project_Edelweiss/Views/Shared/_NavigationMenu.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<nav class="navbar sticky-top navbar-expand-lg navbar-dark">
    <div class="container">
        @if (ViewBag.Logo != null)
        {
            <img class="navbar-brand" src="@ViewBag.Logo" alt="logo">
        }
        @*<a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="@ViewBag.Logo" alt="logo" width="60" height="60"></a>*@
    
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @Localizer["Profile"] @User.Identity.Name
                    </a>
                    <div class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-controller="Account" asp-action="Logout">@Localizer["Exit"]</a>
                    </div>
                </li>
                @*if (ViewBag.Logo != null)
                    {
                        <li><img src="@ViewBag.Logo" alt="logo" width="60" height="60"></li>
                    }*@
                @*@if (!User.Identity.IsAuthenticated)
                {
                    <li class="nav-item"><a href="#exampleModal" class="nav-link" data-toggle="modal" data-target="#exampleModal">@Localizer["Cabinet"]</a></li>
                }
                else
                {
                    
                }*@

            </ul>
        </div>
    </div> <!---container-->
</nav>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@Localizer["Autorization"]</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Login" asp-controller="Account" asp-antiforgery="true">
                    <div class="form-group">
                        <label class="control-label">@Localizer["Login"]</label>
                        <input name="UserName" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="control-label">@Localizer["Password"]</label>
                        <input type="Password" name="password" class="form-control" />
                    </div>
                    <div class="modal-footer">
                        <input type="submit" value="@Localizer["Enter"]" class="btn btn-sm btn-danger" />
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer["Close"]</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>